name = "MLCore"
uuid = "c2834f40-e789-41da-a90e-33b280584a8c"
authors = ["Carlo Lucibello <carlo.lucibello@gmail.com> and contributors"]
version = "1.0.0"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataAPI = "1"
SimpleTraits = "0.9"
Tables = "1"
julia = "1.6"
