name = "MLCore"
uuid = "c2834f40-e789-41da-a90e-33b280584a8c"
authors = ["Carlo Lucibello <carlo.lucibello@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
